const ADD_EXP = 'ADD_EXP'
const ADD_GOLD = 'ADD_GOLD'
const ADD_S0 = 'ADD_S0'
const ADD_S1 = 'ADD_S1'
const ADD_S8 = 'ADD_S8'
const UPDATE_NAME = 'UPDATE_NAME'
const TOGGLE_MODAL = 'TOGGLE_MODAL'
const RESTART_SESSION = 'RESTART_SESSION'
const UPDATE_NETWORK = 'UPDATE_NETWORK'
const LOAD_LANGUAGE = 'LOAD_LANGUAGE'
const LOAD_SHORTKEYS = 'LOAD_SHORTKEYS'
const ADD_SHORTKEY = 'ADD_SHORTKEY'

export default {
    ADD_EXP,
    ADD_GOLD,
    ADD_S0,
    ADD_S1,
    ADD_S8,
    UPDATE_NAME,
    TOGGLE_MODAL,
    RESTART_SESSION,
    UPDATE_NETWORK,
    LOAD_LANGUAGE,
    LOAD_SHORTKEYS,
    ADD_SHORTKEY
}